---
title       : Shiny stocks presentation
subtitle    : An app that displays informations about the stock market
author      : Mickael Burguet
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
logo        : logo.jpg
---

## Presentation

### App description
- The "Shiny stocks" app will allow you to choose a stock market symbol, and it will then displays the stock's price evolution graph, along with the last dividend of the stock.
You will also be able to choose technical indicators to show on the graph. (More about this on the 5th slide)

### You can access the app at this URL: 
- *http://und1f.shinyapps.io/shiny-stocks/*

### All the source code is available on github
- You can clone the repository wih the following command:

```
git clone https://github.com/und1f/shiny-stocks
```

--- .class #id 

## R Library: quantmod

- The app uses a package called quantmod.

- This package is a quantitative financial modelling and trading framework.

- It is used to draw the stocks price graph and to get the last given dividend.

- quantmod can also be used to develop, test and deploy statistically based trading models.


--- .class #id 


## Dataset presentation

- The price evolution dataset looks like this :

```{r}
suppressMessages(library(quantmod))
tmp = getSymbols("GOOG")
head(GOOG, n=4)
```

--- .class #id 


## Technical indicators: definition

### A technical indicator is a result of mathematical calculations based on indications of price and/or volume. The values obtained are used to forecast probable price changes. There are many technical indicators already developed. The two indicators used in the app are described below.

<strong>Moving Average</strong>

- A moving average is a calculation to analyze data points by creating a series of averages of different subsets of the full data set. The app uses a 10 days moving average.

<strong>Bollinger Bands</strong>

- A band plotted two standard deviations away from a simple moving average. In this app, the price of the stock is banded by an upper and lower band along with a 5-day moving average.

